---
- name: Nerdyhamster.net Server provision
  hosts: all
  tags: always
  become: true

  pre_tasks:
    - name: pre-run | [Debian...] update package cache
      tags: always
      apt:
        update_cache: yes
      changed_when: False
      when: ansible_distribution in ["Debian", "Ubuntu"]


- hosts: all
  tags: base
  become: true
  roles:
    - role: base
      vars:
        user: leo
        ssh_key: ~/.ssh/id_ed25519.pub
        ssh_port: 4422

    - role: base
      vars:
        user: ansible
        ssh_key: ~/.ssh/id_ed25519.pub
        ssh_port: 4422
