---
- name: Update all packages to their latest version
  tags: base, update, system
  apt:
    name: "*"
    state: latest

- name: Import user task
  tags: base, user
  import_tasks: user.yml

- name: Import ssh task
  tags: base, ssh
  import_tasks: ssh.yml
